AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  athena-connector-udf-example

Globals:
  Function:
    Timeout: 20

Resources:
  AthenaUDFExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: athena-connector-udf-example
      CodeUri: AthenaConnectorUDFExampleFunction
      Handler: net.sambaiz.athena_connector_udf_example.App
      Runtime: java11
      MemorySize: 512